<div class="sidenav">
  <a href="forside.php">Forside</a>
    
        <button class="dropdown-btn">Webudvikling<i class="fa fa-caret-down"></i>
        </button>
  <div class="dropdown-container">
    <a href="HTML.php">HTML</a>
    <a href="tags.php">Tags</a>
    <a href="attributter.php">Attributter</a>
    <a href="#">CSS</a>
    <a href="internettetshistorie.php">Internettets<br>historie</a>
    <a href="seo.php">SEO</a>
    <a href="server.php">Server<br>begrebet</a>
    <a href="versionsstyring.php">Verssions<br>styring</a>
    <a href="#">Serverside scripting</a>
  </div>
      <button class="dropdown-btn">Design<i class="fa fa-caret-down"></i>
  </button>
    <div class="dropdown-container">
        <a href="#">IA</a>
        <a href="#">Fotografi</a>
        <a href="illustrator.php">Illustrator</a>
        <a href="#">Photoshop</a>
        <a href="#">Farver</a>
        <a href="#">Typografi</a>
        <a href="#">Gestaltlove</a>
        <a href="#">Moodboards</a>
        <a href="#">Styletiles</a>
        <a href="#">Informations<br>arkitektur</a>
    </div>
    <button class="dropdown-btn">Virksomheds<br>forståelse<i class="fa fa-caret-down"></i>
  </button>
     <div class="dropdown-container">
         <a href="#">Præsentations<br>teknik</a>
         <a href="#">Paradigmer</a>
         <a href="#">Kvantitativ</a>
         <a href="#">Kvalitativ</a>
         <a href="#">Brugertest</a>
         <a href="#">Tekst<br>produktion</a>
         <a href="#">BMC</a>
         <a href="#">Value<br>proposition</a>
         <a href="#">Ophavsret og<br>licens</a>
         <a href="#">Transkribering</a>
    </div>
    <button class="dropdown-btn">Projekter<i class="fa fa-caret-down"></i>
  </button>
    <div class="dropdown-container">
        <a href="#">HTML/CSS<br>workshop</a>
        <a href="#">Design thinking</a>
        <a href="#">One page</a>
    </div>
        <a href="#">Om siden</a>
        <a href="#">Kontakt</a>
        <a href="#">Kildeliste</a>
    </div>