<div class="sidenav">
  <a href="forside.php">Forside</a>
    
        <button class="dropdown-btn">Webudvikling<i class="fa fa-caret-down"></i>
        </button>
  <div class="dropdown-container">
    <a href="HTML.php">HTML</a>
    <a href="tags.php">Tags</a>
    <a href="attributter.php">Attributter</a>
    <a href="#">CSS</a>
    <a href="internettetshistorie.php">Internettets<br>historie</a>
    <a href="seo.php">SEO</a>
    <a href="server.php">Server<br>begrebet</a>
    <a href="versionsstyring.php">Verssions<br>styring</a>
    <a href="#">Serverside scripting</a>
  </div>
      <button class="dropdown-btn">Design<i class="fa fa-caret-down"></i>
  </button>
    <div class="dropdown-container">
        <a href="ia.php">Informations<br>arkitektur</a>
        <a href="fotografi.php">Fotografi</a>
        <a href="illustrator.php">Illustrator</a>
        <a href="photo.php">Photoshop</a>
        <a href="farver.php">Farver</a>
        <a href="typografi.php">Typografi</a>
        <a href="gestalt.php">Gestaltlovene</a>
        <a href="moodboard.php">Moodboards</a>
        <a href="styletiles.php">Styletiles</a>
    </div>
    <button class="dropdown-btn">Virksomheds<br>forståelse<i class="fa fa-caret-down"></i>
  </button>
     <div class="dropdown-container">
        <a href="antagelser.php">De 5 grund<br>antagelser</a>
         <a href="#">Præsentations<br>teknik</a>
         <a href="#">Paradigmer</a>
         <a href="kvantitativ.php">Kvantitativ</a>
         <a href="kvalitativ.php">Kvalitativ</a>
         <a href="brugertest.php">Brugertest</a>
         <a href="#">Tekst<br>produktion</a>
         <a href="#">BMC</a>
         <a href="#">Value<br>proposition</a>
         <a href="ophavsretoglicens.php">Ophavsret og<br>licens</a>
         <a href="transkribering.php">Transkribering</a>
    </div>
    <button class="dropdown-btn">Projekter<i class="fa fa-caret-down"></i>
  </button>
    <div class="dropdown-container">
        <a href="#">HTML/CSS<br>workshop</a>
        <a href="#">Design thinking</a>
        <a href="#">One page</a>
    </div>
        <a href="#">Om siden</a>
        <a href="#">Kontakt</a>
        <a href="#">Kildeliste</a>
    </div>